services:
    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        container_name: todo_app
        depends_on:
            - db
            - redis
        environment:
            DB_USERNAME: root
            DB_PASSWORD: root
            DB_PORT: 5432
            DB_HOST: db
            REDIS_HOST: redis
            REDIS_PASSWORD: null
            REDIS_PORT: 6379

    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www/
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - "8876:80"
        container_name: todo_nginx
        depends_on:
            - app

    db:
        image: postgres:latest
        restart: always
        ports:
            - 8889:5432
        environment:
            POSTGRES_DATABASE: 'todo'
            POSTGRES_USER: 'root'
            POSTGRES_PASSWORD: 'root'
        volumes:
            - ./tmp/db:/var/lib/postgresql/data
        container_name: todo_db

    redis:
        image: redis:7.4-alpine
        restart: always
        ports:
            - '6379:6379'
        volumes:
            - ./redis/data:/redis
